version: '2.1'
services:
  mysql:
    container_name: mysql
    extends:
        file: common.yml
        service: common
    image: yarec/prod_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      st:
        ipv4_address: 172.2.0.22