version: '2.1'
services:
  openresty:
    container_name: ngx
    extends:
        file: common.yml
        service: common
    image: box_openresty
    volumes:
      - /root/.acme.sh:/opt/openresty/nginx/acme
    ports:
      - "80:80"
      - "433:433"
    dns:
      - 172.2.0.2
    environment:
      - verynginx_prefix=/opt/openresty/nginx
      - SERVICE_TAGS=urlprefix-/
      - SERVICE_CHECK_HTTP=/
    networks:
      st:
        ipv4_address: 172.2.0.3

